# Generated by Django 4.1.3 on 2022-11-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingventoryApp', '0003_svuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Active', max_length=15, verbose_name='Visibility'),
        ),
    ]
