# Generated by Django 4.1.3 on 2022-11-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingventoryApp', '0010_alter_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='readStatus',
            field=models.CharField(choices=[('unread', 'unread'), ('read', 'read')], default='request', max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Return', 'Return'), ('Returned', 'Returned')], default='Pending', max_length=15, verbose_name='status'),
        ),
    ]
