# Generated by Django 4.1.3 on 2022-11-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingventoryApp', '0011_notification_readstatus_alter_borrow_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='readStatus',
            field=models.CharField(choices=[('unread', 'unread'), ('read', 'read')], default='request', max_length=15, verbose_name='readStatus'),
        ),
    ]
