# Generated by Django 4.1.3 on 2022-11-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingventoryApp', '0013_alter_notification_readstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Possession', 'Possession'), ('Rejected', 'Rejected'), ('Return', 'Return'), ('Returned', 'Returned')], default='Pending', max_length=15, verbose_name='status'),
        ),
    ]
