# Generated by Django 4.1.3 on 2022-11-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingventoryApp', '0015_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('request', 'request'), ('approved', 'approved'), ('rejected', 'rejected'), ('cancelled', 'cancelled'), ('return', 'return'), ('returned', 'returned')], max_length=15, verbose_name='status'),
        ),
    ]
