# Generated by Django 4.1.3 on 2022-11-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SingventoryApp', '0017_alter_svuser_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='svuser',
            name='activated',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=15, verbose_name='activated'),
        ),
    ]
